const destinations = [
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    region: "asia",
    weather: ["hot_sunny", "rainy_cozy"],
    activities: ["surfing", "wellness_spa", "mountain_hiking", "food_culinary", "scuba_diving"],
    best_months: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    budget_tier: ["budget", "midrange", "luxury"],
    avg_flight_from_seoul_usd: 420,
    avg_hotel_budget_usd: 25,
    avg_hotel_mid_usd: 80,
    avg_hotel_luxury_usd: 300,
    group_scores: { solo: 85, couple: 90, family: 65, group: 80 },
    vibe_tags: ["chill", "adventure", "romance"],
    description: "A tropical paradise blending ancient temples, emerald rice terraces, and world-class surf breaks with a deeply spiritual culture. Perfect for those seeking both adventure and inner peace.",
    highlights: ["Ubud rice terraces & monkey forest", "Sunset surf at Uluwatu", "Seminyak beach clubs", "Balinese temple ceremonies", "Cooking class in Ubud"],
    best_neighborhoods: ["Ubud for culture & wellness", "Canggu for surfers & creatives", "Seminyak for luxury dining", "Nusa Dua for resort stays"],
    local_tips: "Rent a scooter, carry a sarong for temples, try nasi goreng from a warung at midnight.",
    image_url: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+bali+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=bali"
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    region: "asia",
    weather: ["mild_pleasant", "cold_crisp"],
    activities: ["food_culinary", "history_culture", "nightlife"],
    best_months: ["Mar", "Apr", "Oct", "Nov"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 250,
    avg_hotel_budget_usd: 60,
    avg_hotel_mid_usd: 150,
    avg_hotel_luxury_usd: 450,
    group_scores: { solo: 92, couple: 85, family: 78, group: 88 },
    vibe_tags: ["culture", "adventure", "explore"],
    description: "A dazzling metropolis where ancient tradition collides with cutting-edge innovation. World-class food, impeccable service, and endless neighborhoods to explore.",
    highlights: ["Shibuya Crossing at night", "Tsukiji fish market morning", "TeamLab digital art", "Akihabara electronics district", "Shinjuku Golden Gai bars"],
    best_neighborhoods: ["Shinjuku for energy & nightlife", "Harajuku for fashion", "Asakusa for tradition", "Shimokitazawa for indie culture"],
    local_tips: "Get a Suica card, eat at standing ramen bars for the best value, visit Senso-ji before 7am.",
    image_url: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+tokyo+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=tokyo"
  },
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    region: "europe",
    weather: ["hot_sunny", "mild_pleasant"],
    activities: ["food_culinary", "history_culture", "nightlife", "surfing"],
    best_months: ["May", "Jun", "Sep", "Oct"],
    budget_tier: ["midrange"],
    avg_flight_from_seoul_usd: 680,
    avg_hotel_budget_usd: 50,
    avg_hotel_mid_usd: 130,
    avg_hotel_luxury_usd: 380,
    group_scores: { solo: 82, couple: 87, family: 70, group: 94 },
    vibe_tags: ["culture", "explore", "romance"],
    description: "Gaudí's city of surreal architecture, golden beaches, and a food scene that never stops. Barcelona lives at full volume from midnight onwards.",
    highlights: ["Sagrada Família light show", "La Boqueria market grazing", "Sunset from Bunkers del Carmel", "El Born tapas crawl", "Barceloneta beach"],
    best_neighborhoods: ["Gothic Quarter for history", "El Born for foodies", "Gràcia for locals", "Barceloneta for beach"],
    local_tips: "Book Sagrada Família tickets 3 weeks ahead, eat dinner after 9pm, avoid Rambla tourist traps.",
    image_url: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+barcelona+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=barcelona"
  },
  {
    id: "kyoto",
    name: "Kyoto",
    country: "Japan",
    region: "asia",
    weather: ["mild_pleasant", "cold_crisp", "rainy_cozy"],
    activities: ["history_culture", "food_culinary", "wellness_spa"],
    best_months: ["Mar", "Apr", "Oct", "Nov"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 280,
    avg_hotel_budget_usd: 50,
    avg_hotel_mid_usd: 130,
    avg_hotel_luxury_usd: 500,
    group_scores: { solo: 88, couple: 95, family: 72, group: 70 },
    vibe_tags: ["culture", "romance", "chill"],
    description: "Japan's cultural soul — 2,000 temples, geisha districts, and bamboo groves that feel like stepping inside a living painting. The most romantic city in Asia.",
    highlights: ["Fushimi Inari at dawn", "Arashiyama bamboo grove", "Tea ceremony in Gion", "Philosopher's Path cherry blossoms", "Kinkaku-ji golden reflection"],
    best_neighborhoods: ["Gion for geisha culture", "Higashiyama for temples", "Arashiyama for nature", "Pontocho for dining"],
    local_tips: "Bicycle is the best transport, book a ryokan for one night, visit Fushimi Inari before 7am.",
    image_url: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+osaka+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=kyoto"
  },
  {
    id: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    region: "africa",
    weather: ["hot_sunny", "mild_pleasant"],
    activities: ["food_culinary", "history_culture", "wellness_spa"],
    best_months: ["Mar", "Apr", "Oct", "Nov"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 780,
    avg_hotel_budget_usd: 20,
    avg_hotel_mid_usd: 70,
    avg_hotel_luxury_usd: 300,
    group_scores: { solo: 70, couple: 88, family: 65, group: 78 },
    vibe_tags: ["culture", "romance", "adventure"],
    description: "A sensory overload of spice-scented souks, mosaic-tiled riads, and the endless theatre of Jemaa el-Fnaa. Otherworldly and completely unforgettable.",
    highlights: ["Getting lost in Medina souks", "Riad rooftop sunset", "Jardin Majorelle blue garden", "Hammam ritual", "Tagine cooking class"],
    best_neighborhoods: ["Medina for authentic immersion", "Gueliz for modern cafes", "Kasbah for quiet luxury"],
    local_tips: "Always negotiate in souks, carry small change, hire a guide for the Medina on day one.",
    image_url: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+marrakech+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=marrakech"
  },
  {
    id: "cape_town",
    name: "Cape Town",
    country: "South Africa",
    region: "africa",
    weather: ["hot_sunny", "mild_pleasant"],
    activities: ["mountain_hiking", "surfing", "food_culinary", "scuba_diving", "nightlife", "wildlife"],
    best_months: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 920,
    avg_hotel_budget_usd: 30,
    avg_hotel_mid_usd: 90,
    avg_hotel_luxury_usd: 280,
    group_scores: { solo: 80, couple: 88, family: 75, group: 85 },
    vibe_tags: ["adventure", "romance", "explore"],
    description: "Where Table Mountain meets two oceans, offering world-class wine, wildlife, and one of the most dramatic coastlines on Earth. Cape Town is simply breathtaking.",
    highlights: ["Table Mountain sunrise hike", "Cape Point lighthouse trail", "Stellenbosch wine tasting", "Boulders Beach penguins", "V&A Waterfront sunset"],
    best_neighborhoods: ["Bo-Kaap for color & culture", "Camps Bay for beach glamour", "Woodstock for street art", "Sea Point for the promenade"],
    local_tips: "Rent a car for the Cape Peninsula, book Table Mountain on a guaranteed clear day, try a braai with locals.",
    image_url: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+cape+town+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=cape+town"
  },
  {
    id: "reykjavik",
    name: "Reykjavik",
    country: "Iceland",
    region: "europe",
    weather: ["cold_crisp"],
    activities: ["mountain_hiking", "wellness_spa", "wildlife"],
    best_months: ["Jun", "Jul", "Aug", "Sep"],
    budget_tier: ["luxury"],
    avg_flight_from_seoul_usd: 850,
    avg_hotel_budget_usd: 80,
    avg_hotel_mid_usd: 200,
    avg_hotel_luxury_usd: 500,
    group_scores: { solo: 85, couple: 92, family: 68, group: 78 },
    vibe_tags: ["adventure", "romance", "chill"],
    description: "Gateway to glaciers, geysers, and the Northern Lights. Iceland's raw, volcanic beauty is unlike anywhere else on Earth — both dramatic and deeply peaceful.",
    highlights: ["Golden Circle day trip", "Blue Lagoon geothermal soak", "Northern Lights chasing", "Glacier hiking on Sólheimajökull", "Whale watching from Reykjavik"],
    best_neighborhoods: ["Downtown 101 for walkability", "Grandi harbor for food halls", "Laugardal for hot springs"],
    local_tips: "Layer up always, rent a 4x4 for the Ring Road, book Blue Lagoon weeks in advance.",
    image_url: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+reykjavik+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=reykjavik"
  },
  {
    id: "maldives",
    name: "Maldives",
    country: "Maldives",
    region: "asia",
    weather: ["hot_sunny"],
    activities: ["scuba_diving", "surfing", "wellness_spa"],
    best_months: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
    budget_tier: ["luxury"],
    avg_flight_from_seoul_usd: 650,
    avg_hotel_budget_usd: 80,
    avg_hotel_mid_usd: 250,
    avg_hotel_luxury_usd: 800,
    group_scores: { solo: 60, couple: 98, family: 70, group: 55 },
    vibe_tags: ["romance", "chill"],
    description: "Overwater villas floating on the most impossibly blue water on Earth. The Maldives exists for one purpose: to make you forget everything else.",
    highlights: ["Overwater villa sunrise", "Manta ray night diving", "Private sandbank picnic", "Underwater restaurant dinner", "Bioluminescent plankton beach"],
    best_neighborhoods: ["North Malé Atoll for accessibility", "Baa Atoll for marine life", "Ari Atoll for diving"],
    local_tips: "Local island guesthouses offer 80% cheaper stays, bring reef-safe sunscreen, seaplane transfers are worth it for the views.",
    image_url: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+maldives+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=maldives"
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    region: "europe",
    weather: ["hot_sunny", "mild_pleasant"],
    activities: ["food_culinary", "history_culture", "nightlife", "surfing"],
    best_months: ["Apr", "May", "Jun", "Sep", "Oct"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 720,
    avg_hotel_budget_usd: 40,
    avg_hotel_mid_usd: 110,
    avg_hotel_luxury_usd: 300,
    group_scores: { solo: 90, couple: 85, family: 72, group: 88 },
    vibe_tags: ["culture", "explore", "chill"],
    description: "Pastel hills, warm pastéis de nata, and fado melodies drifting from old alleyways. Lisbon is Europe's most charming capital — soulful and effortlessly cool.",
    highlights: ["Tram 28 through Alfama", "Pastéis de Belém fresh from the oven", "Miradouro da Graça sunset", "Sintra palaces day trip", "LX Factory Sunday market"],
    best_neighborhoods: ["Alfama for fado & soul", "Bairro Alto for nightlife", "Belém for history", "Príncipe Real for boutiques"],
    local_tips: "Wear flat shoes (cobblestones!), try ginjinha cherry liqueur, take the train to Cascais for a beach day.",
    image_url: "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+lisbon+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=lisbon"
  },
  {
    id: "new_york",
    name: "New York City",
    country: "USA",
    region: "north_america",
    weather: ["cold_crisp", "mild_pleasant"],
    activities: ["food_culinary", "nightlife", "history_culture"],
    best_months: ["Apr", "May", "Sep", "Oct"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 800,
    avg_hotel_budget_usd: 100,
    avg_hotel_mid_usd: 250,
    avg_hotel_luxury_usd: 650,
    group_scores: { solo: 88, couple: 82, family: 80, group: 92 },
    vibe_tags: ["explore", "culture"],
    description: "The city that invented ambition. Every block is a different world, every borough a different energy. NYC doesn't sleep, and neither will you.",
    highlights: ["Central Park in autumn", "Broadway show", "Brooklyn Bridge at sunset", "MoMA & The Met", "Pizza crawl through Brooklyn"],
    best_neighborhoods: ["SoHo for shopping", "Williamsburg for creatives", "West Village for romance", "Lower East Side for nightlife"],
    local_tips: "Get a MetroCard, skip Times Square restaurants, catch free concerts in Central Park in summer.",
    image_url: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+new+york+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=new+york+city"
  },
  {
    id: "patagonia",
    name: "Patagonia",
    country: "Argentina",
    region: "south_america",
    weather: ["cold_crisp", "mild_pleasant"],
    activities: ["mountain_hiking", "fishing", "wildlife"],
    best_months: ["Oct", "Nov", "Dec", "Jan", "Feb"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 1200,
    avg_hotel_budget_usd: 40,
    avg_hotel_mid_usd: 120,
    avg_hotel_luxury_usd: 400,
    group_scores: { solo: 78, couple: 85, family: 60, group: 82 },
    vibe_tags: ["adventure"],
    description: "Jagged granite spires, electric-blue glaciers, and skies so vast they reset your sense of scale. Patagonia is the ultimate frontier for those who need wild.",
    highlights: ["Torres del Paine W Trek", "Perito Moreno Glacier calving", "Los Glaciares boat cruise", "Condor spotting", "Estancia horseback riding"],
    best_neighborhoods: ["El Chaltén for hiking base", "El Calafate for glaciers", "Puerto Natales for Torres del Paine"],
    local_tips: "Book refugios months ahead, pack layers for extreme wind, binoculars are essential for wildlife.",
    image_url: "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+patagonia+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=patagonia"
  },
  {
    id: "dubai",
    name: "Dubai",
    country: "UAE",
    region: "middle_east",
    weather: ["hot_sunny"],
    activities: ["nightlife", "food_culinary", "wellness_spa"],
    best_months: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 550,
    avg_hotel_budget_usd: 60,
    avg_hotel_mid_usd: 160,
    avg_hotel_luxury_usd: 520,
    group_scores: { solo: 72, couple: 80, family: 85, group: 88 },
    vibe_tags: ["explore", "chill"],
    description: "A city that didn't exist 50 years ago and now has the world's tallest building. Dubai is audacious, excessive, and fascinating — spectacle on steroids.",
    highlights: ["Burj Khalifa observation deck at dusk", "Desert safari with dune bashing", "Gold Souk in Deira", "Floating brunch on the Creek", "Ski Dubai indoor slopes"],
    best_neighborhoods: ["Downtown for skyline views", "JBR for beach life", "Old Dubai for culture", "Dubai Marina for dining"],
    local_tips: "Visit during Dubai Shopping Festival (Jan-Feb), dress modestly in old areas, use the Metro to avoid traffic.",
    image_url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+dubai+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=dubai"
  },
  {
    id: "chiang_mai",
    name: "Chiang Mai",
    country: "Thailand",
    region: "asia",
    weather: ["hot_sunny", "rainy_cozy"],
    activities: ["food_culinary", "history_culture", "wellness_spa", "mountain_hiking"],
    best_months: ["Nov", "Dec", "Jan", "Feb"],
    budget_tier: ["budget"],
    avg_flight_from_seoul_usd: 350,
    avg_hotel_budget_usd: 15,
    avg_hotel_mid_usd: 45,
    avg_hotel_luxury_usd: 150,
    group_scores: { solo: 92, couple: 80, family: 70, group: 78 },
    vibe_tags: ["culture", "chill", "adventure"],
    description: "Northern Thailand's soul city — misty mountains, 300 ancient temples, and the best cooking classes in Asia. Chiang Mai moves at a beautifully slow pace.",
    highlights: ["Doi Suthep temple at sunrise", "Thai cooking class", "Sunday Walking Street market", "Elephant Nature Park", "Night Bazaar lanterns"],
    best_neighborhoods: ["Old City for temples", "Nimmanhaemin for cafes & art", "Riverside for calm", "Santitham for local life"],
    local_tips: "Scooter is king, always remove shoes at temples, try khao soi (northern curry noodle) for your first meal.",
    image_url: "https://images.unsplash.com/photo-1512580539-c898c01dc01d?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+chiang+mai+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=chiang+mai"
  },
  {
    id: "santorini",
    name: "Santorini",
    country: "Greece",
    region: "europe",
    weather: ["hot_sunny"],
    activities: ["food_culinary", "wellness_spa"],
    best_months: ["May", "Jun", "Sep", "Oct"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 750,
    avg_hotel_budget_usd: 60,
    avg_hotel_mid_usd: 200,
    avg_hotel_luxury_usd: 600,
    group_scores: { solo: 65, couple: 98, family: 55, group: 60 },
    vibe_tags: ["romance", "chill"],
    description: "White cubic houses cascading over a volcanic caldera, the most celebrated sunset in the Mediterranean, and wine from volcanic grapes. Santorini is unashamedly romantic.",
    highlights: ["Oia sunset from castle ruins", "Caldera catamaran cruise", "Santo Wines tasting", "Red Beach hike", "Fresh seafood in Ammoudi Bay"],
    best_neighborhoods: ["Oia for iconic sunsets", "Fira for nightlife", "Imerovigli for quiet luxury", "Akrotiri for archaeology"],
    local_tips: "Stay in Imerovigli to avoid Oia crowds, rent an ATV to explore the island, book sunset dinner at 5pm.",
    image_url: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+santorini+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=santorini"
  },
  {
    id: "cusco",
    name: "Cusco",
    country: "Peru",
    region: "south_america",
    weather: ["cold_crisp", "mild_pleasant"],
    activities: ["mountain_hiking", "history_culture", "food_culinary"],
    best_months: ["May", "Jun", "Jul", "Aug", "Sep"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 1050,
    avg_hotel_budget_usd: 15,
    avg_hotel_mid_usd: 55,
    avg_hotel_luxury_usd: 220,
    group_scores: { solo: 80, couple: 82, family: 68, group: 85 },
    vibe_tags: ["adventure", "culture"],
    description: "The ancient Inca capital at 3,400m — gateway to Machu Picchu and living museum of pre-Columbian civilization. Every stone street tells a thousand-year story.",
    highlights: ["Machu Picchu via Inca Trail", "Sacred Valley day trip", "Rainbow Mountain hike", "Peruvian food scene", "Plaza de Armas twilight"],
    best_neighborhoods: ["San Blas for artisans & views", "Centro for colonial grandeur", "San Cristóbal for quiet"],
    local_tips: "Acclimatize 2 days before hiking, chew coca leaves for altitude, book Inca Trail permits 6 months ahead.",
    image_url: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+cusco+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=cusco"
  },
  {
    id: "costa_rica",
    name: "Costa Rica",
    country: "Costa Rica",
    region: "south_america",
    weather: ["hot_sunny", "rainy_cozy"],
    activities: ["surfing", "mountain_hiking", "scuba_diving", "wellness_spa", "fishing", "wildlife"],
    best_months: ["Dec", "Jan", "Feb", "Mar", "Apr"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 980,
    avg_hotel_budget_usd: 30,
    avg_hotel_mid_usd: 90,
    avg_hotel_luxury_usd: 280,
    group_scores: { solo: 82, couple: 85, family: 88, group: 88 },
    vibe_tags: ["adventure", "chill"],
    description: "Pura Vida! Two coastlines, cloud forests, and volcanoes — Costa Rica packs more biodiversity per square mile than almost anywhere on Earth.",
    highlights: ["Arenal Volcano hot springs", "Monteverde cloud forest zip-lining", "Manuel Antonio wildlife", "Surfing at Santa Teresa", "Sea turtle nesting at Tortuguero"],
    best_neighborhoods: ["Arenal for adventure", "Manuel Antonio for beach & wildlife", "Monteverde for nature", "Santa Teresa for surf culture"],
    local_tips: "Rent a 4x4, carry rain gear year-round, try a casado (traditional rice & bean plate) at a soda.",
    image_url: "https://images.unsplash.com/photo-1518259102261-b40117eabbc0?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+costa+rica+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=costa+rica"
  },
  {
    id: "hanoi",
    name: "Hanoi & Ha Long Bay",
    country: "Vietnam",
    region: "asia",
    weather: ["hot_sunny", "rainy_cozy", "mild_pleasant"],
    activities: ["food_culinary", "history_culture", "fishing"],
    best_months: ["Oct", "Nov", "Mar", "Apr"],
    budget_tier: ["budget"],
    avg_flight_from_seoul_usd: 300,
    avg_hotel_budget_usd: 15,
    avg_hotel_mid_usd: 50,
    avg_hotel_luxury_usd: 180,
    group_scores: { solo: 88, couple: 82, family: 75, group: 85 },
    vibe_tags: ["culture", "adventure", "explore"],
    description: "Ancient Hanoi's beautiful chaos meets the ethereal karst towers of Ha Long Bay. Vietnam at its most captivating — cheap, vibrant, and impossible to forget.",
    highlights: ["Ha Long Bay overnight cruise", "Old Quarter street food walk", "Ho Chi Minh Mausoleum", "Ninh Binh rice paddy cycling", "Egg coffee at Cafe Giang"],
    best_neighborhoods: ["Old Quarter for energy", "West Lake for calm", "French Quarter for architecture"],
    local_tips: "Cross roads slowly and steadily, try bún chả for lunch, bargain hard at markets, book Ha Long Bay via reputable operator.",
    image_url: "https://images.unsplash.com/photo-1528127269322-539801943592?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+hanoi+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=hanoi"
  },
  {
    id: "buenos_aires",
    name: "Buenos Aires",
    country: "Argentina",
    region: "south_america",
    weather: ["hot_sunny", "mild_pleasant"],
    activities: ["food_culinary", "nightlife", "history_culture"],
    best_months: ["Mar", "Apr", "Oct", "Nov"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 1100,
    avg_hotel_budget_usd: 25,
    avg_hotel_mid_usd: 70,
    avg_hotel_luxury_usd: 200,
    group_scores: { solo: 85, couple: 88, family: 65, group: 90 },
    vibe_tags: ["explore", "romance", "culture"],
    description: "The Paris of South America — passionate tango, world-class steakhouses, and grand boulevards with a rebellious, melancholic edge. Buenos Aires gets under your skin.",
    highlights: ["Live tango show in San Telmo", "Asado at a traditional parrilla", "La Boca's Caminito", "Recoleta Cemetery", "Sunday San Telmo antique market"],
    best_neighborhoods: ["Palermo for trendy dining", "San Telmo for tango", "Recoleta for elegance", "La Boca for color"],
    local_tips: "Bring US dollars, eat dinner after 10pm like locals, catch a live milonga (tango) not a tourist show.",
    image_url: "https://images.unsplash.com/photo-1589409514187-c21d14df0d04?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+buenos+aires+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=buenos+aires"
  },
  {
    id: "zanzibar",
    name: "Zanzibar",
    country: "Tanzania",
    region: "africa",
    weather: ["hot_sunny"],
    activities: ["scuba_diving", "food_culinary", "history_culture", "fishing", "wellness_spa"],
    best_months: ["Jun", "Jul", "Aug", "Sep", "Jan", "Feb"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 880,
    avg_hotel_budget_usd: 20,
    avg_hotel_mid_usd: 80,
    avg_hotel_luxury_usd: 300,
    group_scores: { solo: 75, couple: 92, family: 70, group: 78 },
    vibe_tags: ["romance", "chill", "adventure"],
    description: "Spice island paradise — powder-white beaches, Stone Town's labyrinthine alleys, and the scent of cloves on trade winds. Zanzibar is a world unto itself.",
    highlights: ["Stone Town spice tour", "Nakupenda sandbank day trip", "Jozani Forest red colobus monkeys", "Forodhani Night Market seafood", "Mnemba Atoll snorkeling"],
    best_neighborhoods: ["Stone Town for culture", "Nungwi for beach life", "Paje for kite surfing", "Matemwe for seclusion"],
    local_tips: "Cover up in Stone Town, try Zanzibar pizza at the night market, book a dhow sunset sail.",
    image_url: "https://images.unsplash.com/photo-1586861203927-800a5acdcc4d?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+zanzibar+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=zanzibar"
  },
  {
    id: "queenstown",
    name: "Queenstown",
    country: "New Zealand",
    region: "oceania",
    weather: ["cold_crisp", "mild_pleasant"],
    activities: ["mountain_hiking", "fishing", "surfing", "wildlife"],
    best_months: ["Dec", "Jan", "Feb", "Mar"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 900,
    avg_hotel_budget_usd: 50,
    avg_hotel_mid_usd: 140,
    avg_hotel_luxury_usd: 380,
    group_scores: { solo: 80, couple: 85, family: 78, group: 90 },
    vibe_tags: ["adventure"],
    description: "The adventure capital of the world — bungee jumping, jet boating, and jaw-dropping alpine lakes framed by the Remarkables. Queenstown rewards the brave.",
    highlights: ["Milford Sound fjord cruise", "Bungee jump at Kawarau Bridge", "Routeburn Track day hike", "Central Otago wine tasting", "Skyline Gondola at sunset"],
    best_neighborhoods: ["Queenstown CBD for nightlife", "Arrowtown for charm", "Glenorchy for wilderness", "Frankton for lake views"],
    local_tips: "Book Milford Sound early, bring sandfly repellent, try a Fergburger — it's legendary for a reason.",
    image_url: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+queenstown+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=queenstown"
  },
  {
    id: "jordan",
    name: "Petra & Wadi Rum",
    country: "Jordan",
    region: "middle_east",
    weather: ["hot_sunny", "mild_pleasant"],
    activities: ["history_culture", "mountain_hiking", "wildlife"],
    best_months: ["Mar", "Apr", "Oct", "Nov"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 700,
    avg_hotel_budget_usd: 25,
    avg_hotel_mid_usd: 80,
    avg_hotel_luxury_usd: 250,
    group_scores: { solo: 80, couple: 85, family: 78, group: 82 },
    vibe_tags: ["adventure", "culture"],
    description: "Rose-red Petra carved into cliffsides by the Nabataeans. Blood-red Wadi Rum deserts that feel like Mars. Jordan is one of history's most spectacular stages.",
    highlights: ["Petra by candlelight", "Dead Sea floating experience", "Wadi Rum desert camping under stars", "Roman ruins at Jerash", "Amman Citadel sunset"],
    best_neighborhoods: ["Rainbow Street in Amman", "Wadi Musa for Petra access", "Aqaba for Red Sea diving"],
    local_tips: "Buy the Jordan Pass (visa + sites), spend 2 days at Petra minimum, sleep in a Bedouin camp in Wadi Rum.",
    image_url: "https://images.unsplash.com/photo-1579606032821-4e6161c81571?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+amman+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=petra+jordan"
  },
  {
    id: "hawaii",
    name: "Maui",
    country: "USA",
    region: "north_america",
    weather: ["hot_sunny", "mild_pleasant"],
    activities: ["surfing", "mountain_hiking", "scuba_diving", "wellness_spa", "fishing"],
    best_months: ["Apr", "May", "Sep", "Oct", "Nov"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 700,
    avg_hotel_budget_usd: 80,
    avg_hotel_mid_usd: 220,
    avg_hotel_luxury_usd: 550,
    group_scores: { solo: 75, couple: 92, family: 88, group: 80 },
    vibe_tags: ["chill", "adventure", "romance"],
    description: "Volcanic mountains, rainbow eucalyptus forests, and the world's best surfing beaches. Maui is nature's masterpiece in the Pacific — wild yet paradisiacal.",
    highlights: ["Haleakalā sunrise above the clouds", "Road to Hana drive", "Molokini Crater snorkeling", "Big Beach sunset", "Lahaina fish tacos"],
    best_neighborhoods: ["Wailea for luxury resort life", "Kihei for great value", "Paia for hippie charm", "Kapalua for seclusion"],
    local_tips: "Book Haleakalā sunrise permits 60 days ahead, drive Road to Hana early, try poke from a roadside stand.",
    image_url: "https://images.unsplash.com/photo-1542259009477-d625272157b7?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+maui+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=maui+hawaii"
  },
  {
    id: "london",
    name: "London",
    country: "United Kingdom",
    region: "europe",
    weather: ["rainy_cozy", "mild_pleasant", "cold_crisp"],
    activities: ["history_culture", "food_culinary", "nightlife"],
    best_months: ["May", "Jun", "Jul", "Aug", "Sep"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 650,
    avg_hotel_budget_usd: 70,
    avg_hotel_mid_usd: 180,
    avg_hotel_luxury_usd: 500,
    group_scores: { solo: 88, couple: 80, family: 85, group: 90 },
    vibe_tags: ["culture", "explore"],
    description: "Centuries of history colliding with relentless modernity. London's museums, theatre, food markets, and parks make it endlessly explorable at any pace.",
    highlights: ["Tower of London Crown Jewels", "West End theatre show", "Borough Market food tour", "Sky Garden free admission", "Notting Hill on Sunday"],
    best_neighborhoods: ["Shoreditch for creative energy", "South Bank for culture", "Notting Hill for charm", "Soho for nightlife"],
    local_tips: "Get an Oyster card, most major museums are free, eat at a proper caff for full English breakfast.",
    image_url: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+london+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=london"
  },
  {
    id: "sri_lanka",
    name: "Sri Lanka",
    country: "Sri Lanka",
    region: "asia",
    weather: ["hot_sunny", "rainy_cozy"],
    activities: ["surfing", "history_culture", "food_culinary", "wellness_spa", "mountain_hiking", "fishing", "wildlife"],
    best_months: ["Dec", "Jan", "Feb", "Mar"],
    budget_tier: ["budget"],
    avg_flight_from_seoul_usd: 500,
    avg_hotel_budget_usd: 15,
    avg_hotel_mid_usd: 50,
    avg_hotel_luxury_usd: 200,
    group_scores: { solo: 85, couple: 82, family: 75, group: 80 },
    vibe_tags: ["adventure", "culture", "chill"],
    description: "The teardrop of India — ancient temples, misty tea plantations, wild elephants, and golden beaches. Sri Lanka packs extraordinary variety into a small island.",
    highlights: ["Scenic train through tea country", "Sigiriya Rock Fortress", "Mirissa whale watching", "Galle Fort sunset", "Ella Nine Arches Bridge"],
    best_neighborhoods: ["Galle for colonial charm", "Ella for mountain magic", "Unawatuna for beach", "Kandy for culture"],
    local_tips: "Take the scenic train (not bus), dress modestly at temples, try hoppers with egg for breakfast.",
    image_url: "https://images.unsplash.com/photo-1586613835341-c831da89e411?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+colombo+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=sri+lanka"
  },
  {
    id: "mexico_city",
    name: "Mexico City",
    country: "Mexico",
    region: "north_america",
    weather: ["mild_pleasant"],
    activities: ["food_culinary", "history_culture", "nightlife"],
    best_months: ["Mar", "Apr", "May", "Oct", "Nov"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 900,
    avg_hotel_budget_usd: 25,
    avg_hotel_mid_usd: 70,
    avg_hotel_luxury_usd: 220,
    group_scores: { solo: 85, couple: 80, family: 72, group: 90 },
    vibe_tags: ["culture", "explore"],
    description: "Aztec ruins beneath a 500-year-old Spanish city, Frida Kahlo murals around every corner, and the hemisphere's most exciting street food scene. CDMX is extraordinary.",
    highlights: ["Teotihuacán pyramids at sunrise", "Frida Kahlo's Casa Azul", "Tacos al pastor at midnight", "Xochimilco floating gardens", "Bellas Artes glass ceiling"],
    best_neighborhoods: ["Roma Norte for dining & bars", "Condesa for parks & cafes", "Coyoacán for art & Frida", "Centro Histórico for history"],
    local_tips: "Eat at taquerías with long lines (sign of quality), use Uber for safety, museums free on Sunday.",
    image_url: "https://images.unsplash.com/photo-1518659526054-190340b32735?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+mexico+city+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=mexico+city"
  },
  {
    id: "phuket",
    name: "Phuket",
    country: "Thailand",
    region: "asia",
    weather: ["hot_sunny"],
    activities: ["surfing", "scuba_diving", "nightlife", "food_culinary", "wellness_spa"],
    best_months: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 380,
    avg_hotel_budget_usd: 20,
    avg_hotel_mid_usd: 60,
    avg_hotel_luxury_usd: 200,
    group_scores: { solo: 82, couple: 80, family: 75, group: 92 },
    vibe_tags: ["adventure", "explore", "chill"],
    description: "Thailand's biggest island — turquoise Andaman waters, white sand beaches, and a nightlife scene that never stops. Phuket is pure hedonistic paradise.",
    highlights: ["Phi Phi Islands speedboat day trip", "Old Phuket Town street art", "Bangla Road nightlife", "Similan Islands dive trip", "Big Buddha hilltop views"],
    best_neighborhoods: ["Patong for nightlife energy", "Kata for families", "Rawai for local life", "Old Town for history"],
    local_tips: "Avoid tuk-tuk scams (agree on price first), visit Phang Nga Bay by longtail boat, eat at local markets.",
    image_url: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+phuket+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=phuket"
  },
  {
    id: "cartagena",
    name: "Cartagena",
    country: "Colombia",
    region: "south_america",
    weather: ["hot_sunny"],
    activities: ["food_culinary", "nightlife", "history_culture", "scuba_diving"],
    best_months: ["Dec", "Jan", "Feb", "Mar"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 1050,
    avg_hotel_budget_usd: 20,
    avg_hotel_mid_usd: 65,
    avg_hotel_luxury_usd: 220,
    group_scores: { solo: 78, couple: 90, family: 70, group: 85 },
    vibe_tags: ["romance", "explore", "culture"],
    description: "Candy-colored colonial walls, Caribbean beaches, and a pulse you feel in your chest. Cartagena is Latin America's most romantic city, shimmering in tropical heat.",
    highlights: ["Old walled city evening stroll", "Rosario Islands day trip", "Street food in Getsemaní", "Sunset cocktails on the wall", "El Totumo mud volcano"],
    best_neighborhoods: ["Walled City for romance", "Getsemaní for street art", "Bocagrande for beach", "Manga for locals"],
    local_tips: "Try ceviche at Bazurto Market, take a chiva party bus at night, visit Walled City on a weekday to skip crowds.",
    image_url: "https://images.unsplash.com/photo-1583531172005-814194e6e917?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+cartagena+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=cartagena+colombia"
  },
  {
    id: "swiss_alps",
    name: "Swiss Alps",
    country: "Switzerland",
    region: "europe",
    weather: ["cold_crisp", "mild_pleasant"],
    activities: ["mountain_hiking", "wellness_spa", "wildlife"],
    best_months: ["Jun", "Jul", "Aug", "Dec", "Jan", "Feb"],
    budget_tier: ["luxury"],
    avg_flight_from_seoul_usd: 750,
    avg_hotel_budget_usd: 80,
    avg_hotel_mid_usd: 200,
    avg_hotel_luxury_usd: 600,
    group_scores: { solo: 78, couple: 90, family: 80, group: 78 },
    vibe_tags: ["romance", "adventure", "chill"],
    description: "Pristine alpine perfection — chocolate-box villages beneath Matterhorn silhouettes, crystal lakes, and wildflower meadows that look painted by God.",
    highlights: ["Jungfraujoch Top of Europe train", "Paragliding over Interlaken", "Eiger Trail hike", "Grindelwald cliff walk", "Fondue in a mountain hut"],
    best_neighborhoods: ["Zermatt for Matterhorn", "Interlaken for adventure", "Grindelwald for views", "Lauterbrunnen for waterfalls"],
    local_tips: "Buy Swiss Travel Pass, carry cash for mountain huts, hike Schynige Platte for wildflower meadows.",
    image_url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+zurich+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=swiss+alps"
  },
  {
    id: "istanbul",
    name: "Istanbul",
    country: "Turkey",
    region: "middle_east",
    weather: ["mild_pleasant", "hot_sunny"],
    activities: ["history_culture", "food_culinary", "wellness_spa"],
    best_months: ["Apr", "May", "Sep", "Oct"],
    budget_tier: ["budget", "midrange"],
    avg_flight_from_seoul_usd: 620,
    avg_hotel_budget_usd: 30,
    avg_hotel_mid_usd: 90,
    avg_hotel_luxury_usd: 280,
    group_scores: { solo: 85, couple: 88, family: 78, group: 82 },
    vibe_tags: ["culture", "romance", "explore"],
    description: "The city that bridges continents — Byzantine domes, Ottoman minarets, and the intoxicating chaos of the Grand Bazaar. Istanbul overwhelms all the senses.",
    highlights: ["Hagia Sophia & Blue Mosque", "Grand Bazaar treasure hunt", "Bosphorus sunset cruise", "Turkish hammam ritual", "Rooftop dinner in Galata"],
    best_neighborhoods: ["Sultanahmet for history", "Beyoğlu for nightlife", "Karaköy for cool cafes", "Üsküdar for local life"],
    local_tips: "Get the IstanbulKart for transport, bargain in the bazaar, try simit (sesame bread) from a street cart for breakfast.",
    image_url: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+istanbul+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=istanbul"
  },
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    region: "europe",
    weather: ["hot_sunny", "mild_pleasant"],
    activities: ["history_culture", "food_culinary"],
    best_months: ["Apr", "May", "Oct"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 700,
    avg_hotel_budget_usd: 55,
    avg_hotel_mid_usd: 150,
    avg_hotel_luxury_usd: 450,
    group_scores: { solo: 80, couple: 90, family: 82, group: 78 },
    vibe_tags: ["romance", "culture"],
    description: "An open-air museum where every cobblestone is layered with millennia of history. Rome feeds you extraordinary food and extraordinary beauty simultaneously.",
    highlights: ["Colosseum & Roman Forum at golden hour", "Vatican Museums & Sistine Chapel", "Trastevere evening wander", "Gelato at Giolitti", "Trevi Fountain at midnight"],
    best_neighborhoods: ["Trastevere for authentic romance", "Prati for the Vatican", "Testaccio for food", "Pigneto for local cool"],
    local_tips: "Pre-book Colosseum and Vatican, eat at restaurants without photos on the menu, drink from Roman water fountains.",
    image_url: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+rome+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=rome"
  },
  {
    id: "namibia",
    name: "Namibia",
    country: "Namibia",
    region: "africa",
    weather: ["hot_sunny"],
    activities: ["wildlife", "mountain_hiking", "road_trips"],
    best_months: ["May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 950,
    avg_hotel_budget_usd: 35,
    avg_hotel_mid_usd: 110,
    avg_hotel_luxury_usd: 350,
    group_scores: { solo: 70, couple: 85, family: 72, group: 78 },
    vibe_tags: ["adventure"],
    description: "Earth's oldest desert meets roaming elephants and blood-red dunes. Namibia is Africa's most photogenic country — raw, vast, and deeply humbling.",
    highlights: ["Sossusvlei red sand dunes at dawn", "Etosha National Park safari", "Skeleton Coast drive", "Fish River Canyon hike", "Himba village visit"],
    best_neighborhoods: ["Windhoek for base camp", "Swakopmund for coastal", "Etosha for wildlife", "Lüderitz for quirkiness"],
    local_tips: "Rent a 4x4 for self-drive safari, carry extra fuel, and visit Sossusvlei at 5am before the heat hits.",
    image_url: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+windhoek+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=namibia"
  },
  {
    id: "singapore",
    name: "Singapore",
    country: "Singapore",
    region: "asia",
    weather: ["hot_sunny", "rainy_cozy"],
    activities: ["food_culinary", "nightlife", "history_culture", "wellness_spa"],
    best_months: ["Feb", "Mar", "Jul", "Aug"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 320,
    avg_hotel_budget_usd: 50,
    avg_hotel_mid_usd: 150,
    avg_hotel_luxury_usd: 450,
    group_scores: { solo: 88, couple: 82, family: 90, group: 85 },
    vibe_tags: ["explore", "culture"],
    description: "Asia's cleanest, most efficient city-state with the world's best hawker food, vertical gardens, and a skyline that genuinely dazzles. Singapore is the future, built today.",
    highlights: ["Gardens by the Bay light show", "Maxwell Food Centre hawker feast", "Chinatown & Little India contrast", "Marina Bay Sands rooftop infinity pool", "Sentosa for beach & thrills"],
    best_neighborhoods: ["Marina Bay for skyline", "Tiong Bahru for indie cool", "Clarke Quay for nightlife", "Katong for Peranakan culture"],
    local_tips: "Carry an umbrella (rains daily), eat at hawker centres not restaurants, MRT goes everywhere.",
    image_url: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+singapore+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=singapore"
  },
  {
    id: "amalfi",
    name: "Amalfi Coast",
    country: "Italy",
    region: "europe",
    weather: ["hot_sunny"],
    activities: ["food_culinary", "wellness_spa", "scuba_diving"],
    best_months: ["May", "Jun", "Sep", "Oct"],
    budget_tier: ["midrange", "luxury"],
    avg_flight_from_seoul_usd: 750,
    avg_hotel_budget_usd: 70,
    avg_hotel_mid_usd: 200,
    avg_hotel_luxury_usd: 600,
    group_scores: { solo: 60, couple: 97, family: 60, group: 65 },
    vibe_tags: ["romance", "chill"],
    description: "Pastel villages clinging to impossible cliffs above turquoise water. The Amalfi Coast is postcard Italy turned up to eleven — extravagant, beautiful, and utterly romantic.",
    highlights: ["Ravello's Villa Rufolo gardens", "Positano sunset aperitivo", "Boat tour to Grotta dello Smeraldo", "Limoncello tasting in Amalfi town", "Path of the Gods hike"],
    best_neighborhoods: ["Positano for glamour", "Ravello for quiet romance", "Amalfi town for center", "Praiano for authentic"],
    local_tips: "Avoid August crowds, hire a private boat for coastal access, try fresh sfogliatella pastry every morning.",
    image_url: "https://images.unsplash.com/photo-1533165959898-e55f14f702fb?w=1200&q=80",
    google_flights_url: "https://www.google.com/travel/flights?q=flights+to+naples+from+seoul",
    booking_url: "https://www.booking.com/searchresults.html?ss=amalfi+coast"
  },
];

export default destinations;